mozilla/fxa-dev

aws/environments/stable.yml
@vladikoff or @dcoates, r? - just picking up train-27 versions in stable.
=> update auth/content to train-27

aws/environments/stable.yml
-> train-28
@dannycoates or @vladikoff - r?
=> train-28 updates

aws/dev.yml, aws/environments/dcoates.yml, aws/local.yml, roles/able/defaults/main.yml, roles/able/files/able.conf, roles/able/handlers/main.yml, roles/able/meta/main.yml, roles/able/tasks/main.yml, roles/able/templates/config.json.j2, roles/able/templates/nginx.conf.j2, roles/able/templates/upstream.conf.j2, roles/content/templates/config.json.j2
This will add the AB test server to fxa-dev.
Loading experiments is still TBD so not ready to merge yet
=> added 'able' ab test server

roles/common/tasks/main.yml
=> upgrade npm to npm@2.4.1

aws/environments/stable.yml
I noticed this was one commit behind head, and that commit has changes for where the config file is located.
@vladikoff r?
=> move to head of oauth branch, to pick up changes in the way config is done

aws/environments/stable.yml
@vladikoff, @dannycoates, @rfk  - r?
=> update {auth,auth_db,content} to train-32

aws/environments/stable.yml
Picks up these changes https://github.com/mozilla/123done/compare/0a6ab3c0bedbc810d5e98047189ae0fbf6df4e85...oauth
=> chore(rp): update to latest 123done for new code that passes train-32 functional tests

roles/oauth/defaults/main.yml, roles/oauth/files/fxa-oauth-server.conf, roles/oauth/handlers/main.yml, roles/oauth/tasks/main.yml, roles/oauth/templates/config.json.j2, roles/oauth/templates/nginx.conf.j2
DON'T MERGE. I have no idea what I'm doing. I feel there should be a little more to mount the servers on their respective paths, but I started flipping tables.
=> add oauth-internal server

aws/environments/latest.yml, roles/notifications/defaults/main.yml, roles/notifications/templates/config.json.j2
=> fixed name collision on auth_public_url

roles/authdb/defaults/main.yml, roles/authdb/templates/config.json.j2
this will go along with https://github.com/mozilla/fxa-auth-db-mysql/pull/29
=> connect db-mysql to notification-server

aws/environments/ux.yml
=> change ux env to point to ux-experiments branch

roles/oauth/templates/upstream.conf.j2
=> fix(oauth): add support for internal developer endpoints

aws/cloudformation/moz-single.json, aws/dev.yml, aws/local.yml, roles/oauth/templates/config.json.j2, roles/rp-untrusted/defaults/main.yml, roles/rp-untrusted/files/fxa-rp-untrusted.conf, roles/rp-untrusted/handlers/main.yml, roles/rp-untrusted/meta/main.yml, roles/rp-untrusted/tasks/main.yml, roles/rp-untrusted/templates/config.json.j2, roles/rp-untrusted/templates/nginx.conf.j2, roles/rp-untrusted/templates/upstream.conf.j2
@dannycoates @jrgm feedback?
Don't merge yet...
=> add untrusted rp

roles/auth/files/fxa-auth-server.conf
=> CONFIG_FILES must now be explictly declared

aws/environments/stable.yml
Just the usual bump, only for auth and content for this train
=> chore(stable): update fxa-{auth,content} to train-38

roles/auth/templates/config.json.j2, roles/customs/templates/config.json.j2
the auth fix is permanent. The customs fix is to be revisited later.
=> Convict cleanup

aws/environments/stable.yml
=> chore(stable): bump versions to train-40 and related

roles/content/files/fxa-content-server.conf
=> fix(content): add production-experiments.json to configuration

roles/basket-proxy/tasks/main.yml
=> fix(basket): notify restart to all basket servers on config change

roles/profile/templates/config.json.j2
To go with https://github.com/mozilla/fxa-profile-server/issues/165.  @vladikoff r?
=> fix(profile): add profile-server config to point to auth server

roles/content/templates/config.json.j2
Let's see if anything organically shows up on latest and stage? 
It's report-only.
=> fix(config): enable CSP report-only, to match production

roles/content/templates/config.json.j2
@vladikoff - r? 
Ooops, I forgot about changing the sample rate for a dev environment.
=> fix(csp): log 100% of incoming reports on fxa-dev

roles/content/files/fxa-content-server.conf
related to https://github.com/mozilla/fxa-content-server/pull/3336, this file is going away (when that PR is merged).
=> chore(awsbox): remove awsbox.json for fxa-content-server

roles/oauth/files/fxa-oauth-server.conf
related to https://github.com/mozilla/fxa-oauth-server/pull/372, removing awsbox config.
r? - @vladikoff
=> chore(awsbox): remove awsbox config for fxa-oauth-server

roles/oauth/templates/config.json.j2
Should be merged along with https://github.com/mozilla/fxa-oauth-server/pull/368
=> feat(openid): add openid connect config for oauth

aws/roles/team/tasks/main.yml
=> Update identity-pubkeys hash to latest version

aws/ansible.cfg
=> fix(ansible): switch control_path for ansible

aws/roles/ses/templates/main.cf.j2
Add a couple of rules used in stage and production to be consistent.
r? - @rfk
=> fix(postfix): add allow_min_user=yes/append_dot_mydomain=no like stage/prod

aws/environments/stable.yml
=> chore(stable): bump versions to train-56 and related

aws/cloudformation/moz-single.json, aws/dev.yml, roles/content/defaults/main.yml, roles/content/templates/config.json.j2
@dannycoates, @vladikoff, or @jrgm - r?
This goes along with https://github.com/mozilla/fxa-content-server/pull/3479
=> feat(content-server): Prepare for deployment of static resources to a CDN

roles/auth/templates/config.json.j2, roles/email/templates/config.json.j2
Connects to https://github.com/mozilla/fxa/issues/138
=> feat(reminders): enable verification reminders

aws/roles/team/tasks/main.yml
pick up updates in identity-pubkeys
=> fix(identity-pubkeys): update git sha of pubkeys

roles/email/files/fxa-auth-mailer.conf, roles/email/tasks/main.yml
Fixes https://github.com/mozilla/fxa-dev/issues/249
=> fix(config): make fxa-auth-mailer use its config

roles/auth/templates/config.json.j2
=> fix(config): enable signin confirmation

aws/environments/content.yml
=> feat(deploy): add a box that works with a local content server

roles/customs/files/fxa-customs-server.conf
=> fix(customs): bump UID_RATE_LIMIT for fxa-dev boxes

roles/content/files/fxa-content-server.conf
=> fix(convict): remove defunct production-locales.json from content CONFIG_FILES

aws/environments/stable.yml
=> chore(stable): update stable versions to train-67 and friends

aws/environments/content.yml, aws/environments/latest4.yml, roles/common/defaults/main.yml, roles/common/tasks/main.yml
=> fix(node): update all envs to node 4.5

roles/common/defaults/main.yml
Coming to a theatre near you soon. r? - @vladikoff
=> fix(node): upgrade to node 4.6.0

roles/auth/templates/config.json.j2
r? - @philbooth 
`latest.dev` is currently broken on this change.
=> fix(auth): update for config change from forceEmailRegex

roles/auth/handlers/main.yml, roles/auth/tasks/main.yml
r? - @rfk 
Need keys to run on fxa-dev boxes (latest.dev).
=> fix(push): generate VAPID keys

roles/auth/templates/config.json.j2
Due to https://github.com/mozilla/fxa-auth-server/pull/1530; @shane-tomlinson r?
=> fix(config): Remove feature-flag config for signin confirmation

roles/oauth/templates/config.json.j2
For https://github.com/mozilla/fxa-oauth-server/pull/428
=> chore(config): allow HTTP redirects in OAuth reliers

roles/auth/templates/config.json.j2, roles/email/templates/config.json.j2
=> chore(config): disable verification reminders for now

roles/auth/templates/config.json.j2, roles/email/templates/config.json.j2
Ref https://github.com/mozilla/fxa-dev/pull/294/files
=> chore(config): enable reminders again

roles/auth/defaults/main.yml, roles/auth/tasks/main.yml, roles/authdb/defaults/main.yml, roles/authdb/tasks/main.yml, roles/basket-proxy/defaults/main.yml, roles/basket-proxy/tasks/main.yml, roles/content/defaults/main.yml, roles/content/tasks/main.yml, roles/customs/defaults/main.yml, roles/customs/tasks/main.yml, roles/mysql/defaults/main.yml, roles/mysql/tasks/main.yml, roles/oauth/defaults/main.yml, roles/oauth/tasks/main.yml, roles/profile/defaults/main.yml, roles/profile/tasks/main.yml, roles/rp/defaults/main.yml, roles/rp/tasks/main.yml
@vladikoff - configurable docker tags
=> fix(ansible): allow setting which docker tag to pull/run

aws/cloudformation/moz-single.json, aws/dev.yml, aws/environments/fxadevtest.yml, aws/environments/test1.yml, aws/environments/test2.yml, aws/environments/test3.yml
CDN is not used in this branch; config variable not needed.
=> fix(cdn): remove cdn_ssl_certificate_id config

README.md, aws/environments/emails3.yml, aws/environments/test3.yml, roles/auth/defaults/main.yml, roles/auth/tasks/main.yml, roles/authdb/defaults/main.yml, roles/authdb/tasks/main.yml, roles/basket-proxy/defaults/main.yml, roles/basket-proxy/tasks/main.yml, roles/content/defaults/main.yml, roles/content/tasks/main.yml, roles/customs/defaults/main.yml, roles/customs/tasks/main.yml, roles/mysql/defaults/main.yml, roles/mysql/tasks/main.yml, roles/oauth/defaults/main.yml, roles/oauth/tasks/main.yml, roles/profile/defaults/main.yml, roles/profile/tasks/main.yml, roles/rp-untrusted/tasks/main.yml, roles/rp/defaults/main.yml, roles/rp/tasks/main.yml
Here you go. (Note: no fine grain on e.g., rp trusted vs rp untrusted, or profile main vs profile worker, but meh).
=> fix(docker): allow optional disabling of some docker containers

roles/auth/templates/config.json.j2
=> fix(auth): use default verificationReminders intervals

roles/auth/tasks/main.yml
Just like https://github.com/mozilla/fxa-dev/commit/215c64fde4a095e38033761c9fe7476a9560d8a6 on master branch
=> fix(sms): use mock sms, like master branch 215c64fde4a095e38033761c9fe7476a9560d8a6

aws/docker-pull.sh, aws/environments/udara.yml, aws/local.yml, roles/sync/defaults/main.yml, roles/sync/meta/main.yml, roles/sync/tasks/main.yml, roles/sync/templates/nginx.conf.j2, roles/sync/templates/syncserver.ini.j2, roles/sync/templates/upstream.conf.j2
Fixes https://github.com/mozilla/fxa-dev/issues/314
=> feat(docker): add syncserver to fxa dev

aws/environments/udara.yml, aws/local.yml, roles/redis/defaults/main.yml, roles/redis/meta/main.yml, roles/redis/tasks/main.yml
Sibling of https://github.com/mozilla/fxa-profile-server/pull/254
=> feat(docker) add redis docker image and role

roles/oauth/templates/config.json.j2
@vladikoff can I please have a localhost dev client on your keys boxs so that I can poke at the various pieces of the protocol here?
=> feat(keys): Add localhost dev client for Firefox Notes scope.

README.md
=> fix(docs): add table of contents to readme

roles/customs/tasks/main.yml
ref mozilla/fxa-content-server#5689
https://github.com/mozilla/fxa-customs-server/pull/218
=> feat(sms): Allow `19164400029` as a non-rate limited phone number.

roles/oauth/templates/config.json.j2
=> fix(config): switch scope tld

aws/docker-pull.sh, aws/local.yml, roles/oauth/tasks/main.yml, roles/verifier/defaults/main.yml, roles/verifier/meta/main.yml, roles/verifier/tasks/main.yml
=> fix(verifier): run and use a local browserid-verifier docker container

roles/oauth/templates/config.json.j2
Per https://github.com/mozilla/fxa-oauth-server/issues/515
=> chore(oauth): Add client config for Mozilla IAM

aws/environments/pushbox.yml
/cc @eoger, this will help us stand up a docker-based dev deployment for the pushbox work.
@vladikoff r?
=> feat(env): Add pushbox dev deployment

roles/auth/defaults/main.yml, roles/auth/tasks/main.yml
=> fix(config): set OAUTH_URL in auth-server

roles/rp-untrusted/templates/config.json.j2, roles/rp/templates/config.json.j2
Port https://github.com/mozilla/fxa-dev/pull/354 to master.
=> fix(rp): Update 123done config to new, simpler set of entries.

roles/rp-untrusted/tasks/main.yml, roles/rp/tasks/main.yml
This reverts commit a9cc83b3e14f0f0fb1f447aae79a2491e6fabec7.
=> Revert "fix(123done): make 123done restart to pick up config file changes (#358)"

roles/rp-untrusted/tasks/main.yml, roles/rp/tasks/main.yml
=> fix(rp): dont run gen_keys enymore

aws/environments/latest.yml, roles/auth/defaults/main.yml
=> Set default `auth_redirect_domain` to domain_name

roles/content/tasks/main.yml
=> Remove old EXPERIMENTS vars
