mozilla/fxa-dev

roles/auth/templates/config.json.j2
In order to test that an email is sent after signing in with an unverified account we need to reduce the blackout period to zero on stage, latest, stable, etc.
Fixes https://github.com/mozilla/fxa-content-server/issues/2033.
@dannycoates r?
=> reduce auth-server smtp blackout period to zero

roles/content/templates/config.json.j2
This new list is copied directly from local.json-dist  in content-server repo. @zaach r?
=> Update supportedLanguages setting in content-server config

roles/authdb/defaults/main.yml, roles/authdb/files/fxa-auth-db-server.conf, roles/authdb/handlers/main.yml, roles/authdb/tasks/main.yml
This switches to using the fxa-auth-db-mysql repo for the auth-db-server, which is how things will be after the land the "reverse backends" branch in https://github.com/mozilla/fxa-auth-db-server/issues/60
I renamed the repo and its associated on-disk files to "fxa-auth-db-mysql" but left other things as "fxa-auth-db-server" since that just seems to read nicer.
@chilts @jrgm r?
=> Switch to fxa-auth-db-mysql for dbserver implementation

roles/common/tasks/main.yml
Today, nodejs 0.12.0 became available on the nodejs servers, which means that nave stable will now install that version. However, some of our modules won't compile with 0.12.0 at the moment, so pin this back to 0.10.36 until we are ready to move to 0.12.
=> [breakfix] pin nodejs nave usemain to 0.10.36

roles/rp/handlers/main.yml
They were previously being put into /home/app, which is not where the code was trying to find them.
@vladikoff r?
=> output these keys into /data/fxa-rp

aws/roles/cron_update/defaults/main.yml, aws/roles/cron_update/tasks/main.yml, roles/customs/defaults/main.yml
This setting was getting clobbered on latest, I changed it to match how the basket queue url is handled.  @jrgm r?
=> Set customs_ban_queue_url when updating via cron

aws/environments/stable.yml
update {auth,content,oauth,fxa-auth-db} to current productions versions, as of today. Note: train-29 is correct for fxa-auth-db-server, which is before the reverse db and lock account changes landed.
=> update {auth,content,oauth,fxa-auth-db} to current productions versions, as of today

roles/oauth/templates/config.json.j2
This is a companion fix to https://github.com/mozilla/fxa-oauth-server/pull/218 where having these keys is now required.
=> explicitly state canGrant:false where it was missing

roles/able/meta/main.yml
This "fixes" https://github.com/mozilla/fxa-dev/issues/102 so changes to `able` don't trigger `oauth` from overwriting changes done by `oauth-console`. The right fix is to use nginx includes, but on the other hand, I'm not sure why `able` is declaring a dependency on `oauth` that the other roles do not declare. I'll look into fixing the nginx config, but this should get the oauth console working for actual use.
=> remove oauth dependency to clear up issue with fxa-oauth-console getting clobbered

roles/oauth/templates/config.json.j2
See https://github.com/mozilla/fxa-oauth-server/issues/224
@seanmonstar is this still the canonical way to add long-lived dev credentials?
=> Add credentials for Firefox Browser Compatibility API

aws/environments/stable.yml
This fixes an issue with the dev oauth console, and does not need
to be deployed to production.  @jrgm r?
=> Bump stable to oauth-server v0.30.3.

roles/able/files/able.conf
Hi @dannycoates. Noticed that able was not starting on fxa-dev boxes.
=> fix(able): change the supervisord startup command to bin/server.js

roles/oauth-console/tasks/main.yml, roles/oauth-console/templates/location.conf.j2, roles/oauth-console/templates/upstream.conf.j2, roles/oauth/defaults/main.yml, roles/oauth/files/fxa-oauth-server.conf, roles/oauth/handlers/main.yml, roles/oauth/tasks/main.yml, roles/oauth/templates/config.json.j2, roles/oauth/templates/nginx.conf.j2, roles/oauth/templates/upstream.conf.j2
This builds on @seanmonstar's work on oauth.
- fixes a port conflict with profile server
- finally separates the fight over nginx config files between oauth and oauth-console
- sets up rules to support the oauth-console with the new oauth-internal server
```
Internal server implements these routes:
GET /v1/clients
POST /v1/client
POST /v1/client/{client_id}
DELETE /v1/client/{client_id}
However, `GET /client` must be routed to the regular
oauth server. So, exactly match `GET /v1/clients` and
condition the proxy_pass on the `/v1/client` method.
```
This passes all the selenium functional tests and the console works correctly.
@dannycoates, @seanmonstar, @vladikoff - look ok?
=> Oauth internal server and works with oauth-console

aws/cloudformation/moz-single.json, aws/dev.yml, aws/environments/dcoates.yml, aws/local.yml, aws/roles/ses/tasks/main.yml, roles/common/tasks/main.yml, roles/notifications/defaults/main.yml, roles/notifications/files/fxa-notification-server.conf, roles/notifications/files/generate_keys.sh, roles/notifications/handlers/main.yml, roles/notifications/meta/main.yml, roles/notifications/tasks/main.yml, roles/notifications/templates/config.json.j2
This adds a new redis elasticache instance and the fxa-notification-server. This config depends on the redis PR of the server, not yet in master https://github.com/mozilla/fxa-notification-server/pull/19
=> added fxa-notification-server

aws/environments/latest.yml
So, the config value for publicUrl started being set to https://latest.dev.lcip.org/ (no /auth) sometime today. Almost certainly something in the notifications changes triggered that but don't quite understand it. 
But for now, setting this explicity in latest.yml, gets the auth server config back to where it was.
=> fix(auth): not sure why, but a value for auth_public_url needs to be set now

aws/environments/stable.yml
The ones with git hashes are the current HEAD of each respective repository.
=> chore(stable): bump all the versions for train-33

aws/cloudformation/moz-single.json, aws/environments/stable.yml
Same old. Not asking for review. 
The ELB Policy update is needed since ELBSecurityPolicy-2015-02 has been removed.
=> update auth and content to train-34, and update ELB Policy to right one

roles/oauth-console/templates/config.json.j2
Requires mozilla/fxa-oauth-server#235
Requires https://github.com/mozilla/fxa-oauth-console/pull/28
Waiting for those PRs first...
=> add internal port config for the oauth console

aws/environments/stable.yml
=> chore(stable): bump content,oauth,profile versions to train-35

roles/oauth/templates/config.json.j2
https://github.com/mozilla/fxa-oauth-server/pull/251 adds a trusted column (actual step one in renaming the whitelisted column). So need to fix this config to match.
=> fix(oauth): fxa-oauth #251 adds a trusted column

aws/environments/stable.yml
This updates to train-36 (or whatever is running in production with train-36 release today).
=> chore(stable): update all versions to train-36 (or latest)

roles/oauth/templates/upstream.conf.j2
Sorry, saw this when it came in and then forgot to come back to it. 
So, `location = /v1/developer` will match exactly `/v1/developer` and nothing else, i.e., it won't match `/v1/developer/activate`. So use a looser match for anything on that path prefix.
=> fix(oauth-console): use low-pri, not exact, match on path /v1/developer

aws/ansible.cfg
I used to have this fixed with a Host pattern in my `.ssh/config`, but switched computers and hit this limit on the length of the socket filename (104 on osx, 108 on linux). Anyways, since the control sockets are going to be put in a (hard-coded) directory of `$HOME/.ansible/cp`, beginning each socket filename with `ansible-ssh-` adds no new information really. So dropping that allows the socket name to be short enough by just a few characters.
r? @vladikoff, @dannycoates
=> fix(ssh): use a shorter ssh control_path setting

aws/cloudformation/moz-single.json, roles/content/defaults/main.yml, roles/content/files/fxa-basket-proxy.conf, roles/content/files/fxa-null-basket.conf, roles/content/handlers/main.yml, roles/content/tasks/main.yml, roles/content/templates/config.json.j2, roles/content/templates/nginx.conf.j2, roles/content/templates/upstream.conf.j2
[DO NOT MERGE YET] - this depends on branches of fxa-content-server to merge to master; without that code landed these changes will have problems since they will try to start programs that dont' exist on master yet. 
Anyways, this change will run the basket proxy server along with the "null server" a simple implementation of the Basket api. You can edit fxa-content-server/server/config/local.json to change api_url and api_token to point at a Basket staging or production server if you wish. 
Note on this change:
fix(elb,tls): update to ELBSecurityPolicy-2015-05 (N.B., may not be compatible with older clients)
We may need to set a custom policy to accomodate Android 2.3, but as of today the 2015-03 is no longer available. So it's either 2015-05 with no DHE, or cannot build a new stack, at …
=> fix(fxa-content): configuration and daemons to support email opt-in

roles/content/templates/config.json.j2
This is unused in current content-server, and causes strict convict mode to throw (not defined in content-server's config schema server/lib/configuration). 
r? @dannycoates
=> fix(config): remove unused config "ab_url"

aws/environments/stable.yml
Just standard bump of versions to train-39, although I'm using the actual tag name instead of head of the train branch (and yes, some tags are 'vM.N.O' and others are 'M.N.O', no 'v').
=> chore(stable): bump versions to train-39 and related

roles/common/tasks/main.yml, roles/sync/tasks/main.yml
I'm pretty sure this is the correct way.
=> fix(symlink): reverse symlink direction of supervisorctl and virtualenv

roles/sync/tasks/main.yml
Nice bit of `pip` magic @dannycoates 
But we also need similar for `virtualenv`, so this is it. 
If I'm wrong again, then just revert me again, but latest.dev.lcip.org is blocked on updates without this
=> fix(pip): make pip install virtualenv in /usr/bin

roles/oauth/templates/config.json.j2
It's going away entirely as of https://github.com/mozilla/fxa-oauth-server/pull/284
@jrgm r?
=> chore(oauth): remove the deprecated "whitelisted" column from oauth clients

roles/oauth/templates/config.json.j2
https://github.com/mozilla/fxa-oauth-server/pull/312 changed to require an `events` config with non-empty `queueUrl` and `region` if "prod" or "stage". latest.dev.lcip.org runs as "stage" so this breaks all oauth functional tests because the oauth server **will not start on latest.dev.lcip.org**. 
**This is not a fix**, just a band-aid that should get content-server functional tests (mostly) passing again. (Seems to be some other test failures, but at least it gets it back to within shooting distance of passing).
=> fix(breakfix): add a placeholder events config to workaround fxa-auth-server#312

roles/sync/tasks/main.yml
@dannycoates - you were right (of course). The pip install of virtualenv does not work with --install-option as expected and keeps putting virtualenv in /usr/local/bin. (I think an upgraded version of pip may fix this bug, but, ugh, what a load of crap).
Anyways, this change will just ignore errors on the symlink. I don't like it a lot, but it solves an immediate problem that `latest.dev.lcip.org` fails to update without this change. 
I also did this by registering the result of `test -f /usr/bin/virtualenv` and only trying the symlink if that file does not already exist. But seemed too much; the symlink is unlikely to fail in the new box case, and it will be quite clear that there's an error when the sync role tries to run virtualenv and can't find it.
=> fix(virtualenv): attempt to symlink virtualenv, but ignore errors

roles/content/tasks/main.yml
I realized we weren't restarting the fxa-basket-proxy and fxa-null-basket when the source code changed. This fixes that.
@dannycoates - r?
=> fix(basket): restart basket-proxy on git change

roles/content/files/fxa-content-server.conf, roles/content/templates/config.json.j2
We should be using the list of locales in production-locales.json on `latest.dev.lcip.org` and other test instances of fxa-dev. Travis-ci already tests the full set of possible locales on every commit to fxa-content-server.
r? - @vladikoff
=> chore(l10n): use production-locales.json

README.md
I know it's mentioned at the end too, but when did *anyone* read all the way to the end of a readme?
=> fix(docs): clarify "meta-" prefix for SSH access

aws/Makefile, aws/roles/cron_update/tasks/main.yml
Fixes #193 (but not with symlink, force the install into /usr/bin)
1. pip install into /usr/bin
2. ansible/python by default buffers; setting unbuffered prints progress as it happens
r? - @dannycoates or @rfk
=> Fix ansible playbook location

aws/cloudformation/moz-single.json, aws/dev.yml, roles/oauth/templates/config.json.j2, roles/profile/templates/config.json.j2
This creates queues for account change notifications for oauth and profile.
Since it is a documented limitation of Cloudformation that you cannot update the subscriptions to a topic once it has been created, this change effectively deletes the previous account change topic and subscribes basket, oauth and profile servers to it. This causes an interruption for a short bit, which couldn't be done in production, but is acceptable for fxa-dev uses.
r? - @rfk or @dannycoates
=> fix(sqs): create account change queues and subscribe oauth and profile

README.md, aws/dev.yml, aws/environments/EXAMPLE.yml, aws/environments/latest.yml, aws/environments/stable.yml
Fixes #173 
A tag set on the cloudformation stack will be propagated down to the EC2 instance. 
Defaults to Owner: "nobody@mozilla.com" and REAPER_SPARE_ME: "false", i.e., reap away (when this is in full effect, but it will warn in advance, so it is recommended to set at least Owner to get a warning, or both if you don't want to be reaped).
=> fix(tags): set Owner and REAPER_SPARE_ME tags

aws/roles/team/tasks/main.yml
Pulls in the latest changes to identity-pubkeys (including my new high-stength RSA key, which is why i noticed this).  @dannycoates r?
=> Use latest git sha for identity-pubkeys repo

roles/auth/templates/nginx.conf.j2, roles/content/templates/nginx.conf.j2
This fixes tests run remotely against latest.dev.lcip.org and other fxa-dev boxes.
r? - @vladikoff, /cc @seanmonstar
=> fix(nginx): use specific route for /.well-known/openid-configuration

roles/content/templates/config.json.j2
Note: latest.dev.lcip.org has not updated fxa-content-server in the last 2 days, since this blocked it.
=> fix: csp.reportSampleRate is obsolete and breaks content startup

roles/oauth/templates/config.json.j2
This PR removes the static openid keys. This PR and https://github.com/mozilla/fxa-oauth-server/pull/378 will fix https://github.com/mozilla/fxa-dev/issues/212
@seanmonstar r?
=> fix(openid): Remove static keys, use generated keys instead

.gitignore, aws/cloudformation/moz-single.json, aws/defaults.yml, aws/dev.yml, aws/local.yml, aws/roles/ses/tasks/main.yml, roles/authdb/handlers/main.yml, roles/authdb/tasks/main.yml, roles/datadog/tasks/main.yml
@dannycoates, @vladikoff - r?
A major set of updates:
- changes the default ec2 instance from m3.medium to t2.small (which counter-intuitively provides better performance in tests I have run, but at a lower cost. The tests also show that they will not run short of CPU credits under typical fxa-dev usage, so no worries about that).
- fixes #174 by inverting the build order of authdb and auth; it's still a bit odd to have authdb peeking at the auth config, but it suffices.
- updates the AMI to use the latest Amazon Linux AMI using HVM (not PV) virtualization.
- the ec2 instance type can now be chosen if t2.small doesn't fit the use case.
- disk size is also now configurable, but almost all use cases of fxa-dev will be fine with the default.
- implicitly updates to boto@2.38.0/python@2.7.10 …
=> [do not merge yet] Newer AMI and optional sizing of instance and disk and some bug fixes

aws/environments/latest4.yml, roles/common/defaults/main.yml, roles/common/tasks/main.yml
Note: this does not produce a successful fxa-dev deploy, since, for one, kibana3 does not build. But this let's me get this change out of a hack branch that I use to run latest4.dev.lcip.org
=> Changes to build with node4

roles/able/files/able.conf, roles/kv/files/fxa-kv-server.conf, roles/log/defaults/main.yml, roles/log/tasks/main.yml
- The changes to `roles/log` are two-fold:
1. Use my fork of kibana to fix an issue with grunt and uglify failing to build the assets with nodejs 4.x.
2. Ensure a version of phantomjs compatible with npm-phantomjs is installed before `npm install` runs. Otherwise, npm-phantomjs would try to install it's own versions, and often fail, breaking the install. I like phantomjs, but can you tell how much I hate this npm module from the comments (and other grunt-contrib-* modules that try to do this sort of tarball-install from npm)?
- The changes to `roles/able` and `roles/kv`, are unrelated to node 4.x. I just had some failures with `npm install` on those roles, but the actual reasons for failing to start were going to /dev/null. So, this just logs the stderr from these services.
I've built new …
=> Some fixes to build with node 4.x, and an unrelated error logging change for able and kv

aws/environments/latest4.yml
Now that branch build_with_nodejs_4x was merged to master, use master branch on latest4.dev.lcip.org
=> fxa(latest4): use fxa-dev/master with latest4

roles/rp-untrusted/templates/config.json.j2
Fixes https://github.com/mozilla/fxa-content-server/issues/3541#issuecomment-189271094
@shane-tomlinson r?
=> fix(oauth): add display_name permission for untrusted 321done

roles/content/handlers/main.yml, roles/content/tasks/main.yml
@vladikoff - something like this might be "good enough" to minimize the minutes-long absence of `./dist` during `grunt build`. 
(An alternative approach would be to keep a permanent `/data/fxa-content-server-build`, `rsync` the running copy after the `git pull`, do the build, and then `rsync` the build directory over the running copy and restart).
=> fix(content): install/build in a copy directory and swap back in

roles/customs/files/fxa-customs-server.conf
r? - @vladikoff @vbudhram 
This value should get tests not failing on 429 errors, so we can see what other test failures exist.
A different number can be picked later.
=> fix(customs): increase MAX_ACCOUNT_STATUS_CHECK to 1000

roles/content/templates/config.json.j2
Goes along with https://github.com/mozilla/fxa-content-server/pull/3627 and https://github.com/mozilla-services/puppet-config/pull/1988
@vladikoff or @jrgm - r?
=> fix(config): Add FxA report-only config options.

aws/defaults.yml
The latest ansible seems to insist on using the system python, rather than the python active in your $PATH at the time it's invoked.  That's no fun when you  don't want to install a bunch of stuff into the crufty old system python on your mac, and would like to use a virtualenv with homebrew instead.
This tweak seems to make it use the python executable found in $PATH, which is much nicer.  I've kicked off a full stack rebuild using this, will update here if it's successful.
=> Use python from $PATH, not system python

roles/auth/templates/config.json.j2
@jrgm or @vladikoff r?
Convict freaks out if we have config options that aren't defined, so we have to remove it here.
=> fix(config): Remove no-longer-supported resendBlackoutPeriod config

aws/cloudformation/moz-single.json, aws/dev.yml, aws/environments/EXAMPLE.yml
* Set up a CNAME to the CDN on static.host.dev.lcip.org
* Tell Cloudfront to use the CNAME
* Tell Cloudfront to use the specified SSL cert
@jrgm, @vladikoff, @dannycoates - I could use some help with this. This patch is to set up the CDN on a dev.lcip.org domain, using our *.dev.lcip.org cert. For the "IamCertificateId", I have tried both the certificate ID for the *.dev.lcip.org cert as reported the AWS CLI, as well as the certificate name. In both cases, the following error is displayed in the AWS console:
```
The specified SSL certificate doesn't exist, isn't valid, or doesn't include a valid certificate chain.
```
I have also tried the Arn, using the [ACMCertificateArn](https://docs.aws.amazon.com/AmazonCloudFront/latest/APIReference/DistributionConfigDatatype.html#DistributionConfigDa …
=> feat(cdn): Deploy static resources to a CDN on a dev.lcip.org domain.

roles/oauth/templates/config.json.j2
I've run into it a couple of times where we hit max_connections on an fxa-dev. 
When it hits the limit (32 given the size of RDS instance), 20 of the connections are consumed by the oauth and oauth-internal daemons. I don't think they really need this many connections, but do so because they are configured to grab 10 in a block. So just lower this to something less greedy.
(The other approach is to change max_connections on RDS to something higher, but that requires created a custom parameter list for RDS and using that list with the instance. It's simpler just to have oauth not be so greedy).
r? - @vladikoff or @seanmonstar
=> fix(oauth): set connectionLimit: 5 to be less greedy

roles/auth/templates/nginx.conf.j2, roles/content/defaults/main.yml, roles/content/templates/config.json.j2, roles/content/templates/nginx.conf.j2
Exposes the `/.well-known/fxa-client-configuration` endpoint that we added in https://github.com/mozilla/fxa-content-server/pull/3919; @vladikoff r?
=> feat(client-config): Add support for /.well-known/fxa-client-configuration

aws/environments/latest.yml
I ran the update on latest.dev.lcip.org stack so it was actually using a CDN. It also needs this change, to configure content-server to use the CDN.
=> fix(content): add CDN config to environments/latest.yml

aws/cloudformation/moz-single.json
Fixes issue where deploying a new box in the dev AWS account you would get
`There is no policy with name ELBSecurityPolicy-2015-05 for load balancer elb-balancer`
=> fix(policy): Update to 2016-8 ELB policy

aws/environments/latest.yml
r? - @rfk 
This may be just for a short-term fix.
The auth-db server is sending larger payloads to the notification server and being rejected. This is spinning a huge amount of CPU and causing other testing to fail.
=> fix(notifications): don't do notifications

roles/auth/templates/config.json.j2
I didn't explain myself very well about how this config setting gets parsed.
Essentially the string will be passed as the argument to the `RegExp` constructor, so the leading and trailing slashes that got added were wrong. In addition to that I've made a couple more tweaks:
* I've escaped the quoting backslashes so that they make it into the parsed regex, rather than a dot literal which matches any character.
* I've moved the starting `^` and terminating `$` matches outside of the group, to try and make the two types of email a little clearer.
@vladikoff, does this fix the problems you're discussing in https://github.com/mozilla/fxa-content-server/issues/4243?
/cc @jrgm
=> fix(config): fix signinConfirmation.enabledEmailAddresses config

roles/auth/templates/config.json.j2
Must merge after https://github.com/mozilla/fxa-auth-server/pull/1471
@seanmonstar, @vladikoff - r?
@vladikoff - when the auth server portion of this lands, we'll need to update latest's config with this change.
=> feat(config): Add signinUnblock auth server config.

roles/auth/templates/config.json.j2
This was originally merged as sha
5d58e970e993a63514012bf544e92e2cfb23ef20, but was backed out
because the auth-server portion had not yet merged. The auth-server has
merged, opening again.
=> feat(config): Add signinUnblock auth server config (again).

roles/email/templates/config.json.j2
The only two locales supported are "en_US" and "de", yet the
defaultLanguage is set to "en". I see a lot of auth-mailer restarts
on fxa-dev when sending verification reminders and am wondering
if this could be a cause.
Instead of using a local set of `locales`, use those from
fxa-shared, which should contain `en` as a language.
@jrgm or @vladikoff - r?
=> fix(mailer): Remove the `locales`, depend on fxa-shared

roles/auth/templates/config.json.j2
With https://github.com/mozilla/fxa-auth-server/pull/1554,
signinUnblock.enabledEmailAddresses was renamed to forcedEmailAddresses.
We need to update it here too!
@vladikoff, @vbudhram, or @seanmonstar - r?
=> fix(auth-server): rename enabledEmailAddresses to forcedEmailAddresses

roles/rp-untrusted/templates/config.json.j2, roles/rp/templates/config.json.j2
These config values are no longer needed, removed in https://github.com/mozilla/123done/pull/158
=> chore(config): remove preverify_email_audience

aws/cloudformation/basic.json, aws/cloudformation/moz-single.json
r? - @vladikoff, @rfk 
Updates AMI to most currently available. Only for new servers; existing unaffected.
=> fix(config): update amzn linux ami ids

roles/auth/defaults/main.yml, roles/auth/templates/config.json.j2
This isn't ready, whenever testing on fxa-ci, `useMock` ends up being `True` instead of `true` #305 
fixes mozilla/fxa-content-server#4890
=> feat(sms): Use a mock SMS provider by default.

roles/auth/templates/config_mailer.json.j2
This is to avoid interfering with functional tests.
@vladikoff - r?
=> fix(test): Only send verification reminder emails after 40 seconds.

roles/auth/tasks/main.yml
I had the syntax wrong in the previous commit, duh.
=> fix(sms): do not use "," in environment config lines

roles/customs/tasks/main.yml
The functional tests that consume signinCodes are being rate limited.
Relax the limit on test environments.
@philbooth - Is this the right field to get around the SMS signinCode consumption rate limiting we saw?
=> fix(SMS): Relax MAX_ACCOUNT_ACCESS for functional tests.

roles/auth/tasks/main.yml
This is to better approximate prod where mozilla.com addresses
were removed from these lists for train-90.
@jbuck and @vladikoff - r?
This is to go along with the cloudops-deployment PR that removed mozilla.com addresses from these lists.
=> fix(customs): remove mozilla.com from force unblock/confirm lists.

roles/authdb/tasks/main.yml
Otherwise you can't deploy a `feature.name` branch of auth-db-mysql that contains a migration, because we run the db-patcher script from the `latest` tag rather than `feature.name`.
=> fix(db-patcher): Use correct docker tag when running db-patcher script.

roles/oauth/templates/config.json.j2
This adds a randomly generated oauth client for iOS. Connects with https://github.com/mozilla/fxa-oauth-server/issues/473
@rfk @vladikoff r?
=> fix(client): Add iOS dev oauth client

roles/rp-untrusted/templates/config.json.j2, roles/rp/templates/config.json.j2
As of https://github.com/mozilla/123done/pull/165 the config for 123done has been greatly simplified, you know only need to specify a single "issuer uri" rather than listing all the services.  @mozilla/fxa-devs r?
=> fix(rp): Update 123done config to new, simpler set of entries.

aws/environments/EXAMPLE.yml, aws/environments/ampy.yml, aws/environments/content.yml, aws/environments/dcoates.yml, aws/environments/emails3.yml, aws/environments/featurebox.yml, aws/environments/fxaci.yml, aws/environments/fxadevtest.yml, aws/environments/ios-push.yml, aws/environments/jrgm2.yml, aws/environments/latest.yml, aws/environments/latest4.yml, aws/environments/latest6.yml, aws/environments/latestd.yml, aws/environments/marketplace.yml, aws/environments/nightly.yml, aws/environments/oauth-sync.yml, aws/environments/rfkelly.yml, aws/environments/stable.yml, aws/environments/stable2.yml, aws/environments/stomlinson.yml, aws/environments/test1.yml, aws/environments/test2.yml, aws/environments/test3.yml, aws/environments/test62.yml, aws/environments/totp.yml, aws/environments/udara.yml, aws/environments/ux.yml, aws/environments/uxwip.yml, aws/environments/vbudhram.yml
r? - @rfk 
`rds_password` is no longer used in the docker branch (not to mention that the databases have no sensitive data or that they can't be accessed externally). So just cleaning these out.
=> chore(rds): remove unreferenced rds_password from aws/environment's

roles/rp-untrusted/tasks/main.yml, roles/rp/tasks/main.yml
So, 123done loads the config file direct from disk (i.e., no convict-style reader). And there's no handler on the template change. I could add the handler but it would be better to teach 123done to use the environment. 
Anyways, in the short term, adding a new env var will cause 123done to restart and pick up the new config on `latest` and other fxa-dev boxes.
r? - @vladikoff
=> fix(123done): make 123done restart to pick up config file changes

aws/environments/fxaci.yml, roles/auth/tasks/main.yml
@vladikoff r?
What would happen if we pointed `fxadev_git_version` to docker branch? Seems like without that, we are running a few updates behind.
=> Update auth-server redirect domain

aws/environments/oauth-sync.yml, roles/content/defaults/main.yml, roles/content/tasks/main.yml
This allows the scoped-keys validation rules to be customized for each dev environment, based on an environment variable.  @vladikoff r?
This took me a lot longer than it should have, because something down inside ansible likes to parse strings starting with "{" into python dicts and then re-render them as strings which are *almost* JSON except for using single quotes and so are rejected by `JSON.parse`.  Causing the string to not start with "{" was the nicest solution I could come up with...
=> feat(keys): Allow configuration of SCOPED_KEYS_VALIDATION object.

aws/cloudformation/moz-single.json
As per the discussion at https://github.com/mozilla/fxa-auth-server/pull/2401#issuecomment-384965557, this PR adds permissions to query AWS for our current spend against the budget.
Tested in the [`sms` branch](https://github.com/mozilla/fxa-dev/compare/docker...sms?expand=1) and running right now as `sms.dev.lcip.org`.
@jbuck r?
=> feat(sms): enable permissions for SMS budget checks
